[package]
name = "server-monitoring"
version = "0.1.0"
edition = "2024"
authors = ["Louis Meyer (H1ghBre4k3r) <h1ghbe4k3r@dev.bre4k3r.de>"]
license = "GPL-3.0"
readme = "README.md"

[dependencies]
anyhow = "1.0.99"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.47", features = ["derive"] }
dotenv = "0.15.0"
reqwest = { version = "0.12.23", features = ["json"] }
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.143"
sysinfo = "0.37.0"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
