services:
  hub:
    image: ghcr.io/h1ghbre4k3r/guardia:latest
    container_name: guardia-hub
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config:ro
      - guardia-data:/app/data
    environment:
      # Optional: Override config file location
      - RUST_LOG=info

volumes:
  guardia-data:
    driver: local

