# Cargo configuration for faster builds

[build]
# Enable incremental compilation (faster rebuilds)
incremental = true

# Parallel jobs (auto-detect CPU count)
# jobs = 4  # Uncomment to limit parallelism

[profile.dev]
# Enable incremental compilation for development
incremental = true

[profile.test]
# Enable incremental compilation for tests
incremental = true

# Optional: Use a faster linker (uncomment if available on your system)
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
#
# [target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
#
# [target.x86_64-pc-windows-msvc]
# linker = "rust-lld.exe"
